version: "2"

linters:
  exclusions:
    paths:
      - pkg/janet/test/module.go

formatters:
  enable:
    - golines
    - gci
  settings:
    golines:
      max-len: 80
    gci:
      sections:
        - standard
        - prefix(github.com/cfoust/cy)
        - default
      custom-order: true
