// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package params

import (
	"database/sql"
)

type Parameter struct {
	Key       string
	Value     []byte
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
