// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package params

import (
	"context"
)

const getParameter = `-- name: GetParameter :one
SELECT value FROM parameters
WHERE key = ?
`

func (q *Queries) GetParameter(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getParameter, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const setParameter = `-- name: SetParameter :exec
INSERT OR REPLACE INTO parameters (key, value)
VALUES (?, ?)
`

type SetParameterParams struct {
	Key   string
	Value []byte
}

func (q *Queries) SetParameter(ctx context.Context, arg SetParameterParams) error {
	_, err := q.db.ExecContext(ctx, setParameter, arg.Key, arg.Value)
	return err
}
